language: php

services:
  - postgresql

matrix:
  include:
    - php: 7.0 # sqlite
      env: DEPENDENCIES='low'
    - php: 7.0

before_install:
  - composer self-update

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - composer run-script test