language: php

services:
  - mysql
  - postgresql

matrix:
  include:
    - php: 7.0
      env:
        - DEPENDENCIES='low'
        - DB='mysql'
    - php: 7.0
      env:
        - DB='pgsql'

before_install:
  - composer self-update
  - if [ "$DB" == "pgsql" ]; then cp etc/travis/parameters.pgsql.yml app/config/parameters.yml; fi;
  - if [ "$DB" == "mysql" ]; then cp etc/travis/parameters.mysql.yml app/config/parameters.yml; fi;

install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" != "low" ]; then composer update; fi;
  - if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest; fi;

script:
  - composer run-script test