services:
  dumplie.twig.loader.file_loader:
    class: Dumplie\SharedKernel\Infrastructure\Twig\DumplieFileLoader
    tags:
      - { name: twig.loader }

  dumplie.twig.twig.extension.rendering:
      class: Dumplie\SharedKernel\Infrastructure\Twig\Extension\RenderingExtension
      public: false
      arguments:
        - "@dumplie.shared_kernel.rendering.context_map"
      tags:
          - { name: twig.extension }